name: "Test app initialization"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
        - main
        - staging

env:
    RPC_URL_11155111: ${{ secrets.RPC_URL_11155111 }}
    RPC_URL_8453: ${{ secrets.RPC_URL_8453 }}
    RPC_URL_84532: ${{ secrets.RPC_URL_84532 }}
    PROVIDER_URI_11155111: ${{ secrets.RPC_URL_11155111 }}
    PROVIDER_URI_8453: ${{ secrets.RPC_URL_8453 }}
    PROVIDER_URI_84532: ${{ secrets.RPC_URL_84532 }}
    PRIVATE_KEY_11155111: ${{ secrets.PRIVATE_KEY_11155111 }}
    PRIVATE_KEY_8453: ${{ secrets.PRIVATE_KEY_8453 }}
    PRIVATE_KEY_84532: ${{ secrets.PRIVATE_KEY_84532 }}
    NEXT_PUBLIC_RPC_URL_11155111: ${{ secrets.RPC_URL_11155111 }}
    NEXT_PUBLIC_RPC_URL_8453: ${{ secrets.RPC_URL_8453 }}
    NEXT_PUBLIC_RPC_URL_84532: ${{ secrets.RPC_URL_84532 }}
    NEXT_PUBLIC_PROVIDER_URI_11155111: ${{ secrets.PROVIDER_URI_11155111 }}
    NEXT_PUBLIC_PROVIDER_URI_8453: ${{ secrets.PROVIDER_URI_8453 }}
    NEXT_PUBLIC_PROVIDER_URI_84532: ${{ secrets.PROVIDER_URI_84532 }}
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}

jobs:
  test:
    name: "axiom-init: Next.js"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check forge version
        run: forge --version

      - name: Install NPM packages
        working-directory: ./axiom-init
        run: npm install

      - name: Build app
        working-directory: ./axiom-init
        run: npm run build

      - name: Initialize app
        working-directory: ./axiom-init
        run: node dist/index.js init -p app-nextjs -s nextjs -m npm -c 11155111

      - name: Forge test
        working-directory: ./axiom-init/app-nextjs
        run: forge test -vvv

      - name: Compile circuit
        working-directory: ./axiom-init/app-nextjs
        run: npx axiom circuit compile app/axiom/average.circuit.ts -p ${{ env.RPC_URL_11155111 }} --force

      - name: Build Next.js app
        working-directory: ./axiom-init/app-nextjs/app
        run: npm run build
